name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - Phase05

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install -B

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: mohaymen-academy
          token: ${{ secrets.SONAR_TOKEN }}  # Make sure to set the 'SONAR_TOKEN' secret in your repository settings

